Create toaster component
kodiak-packages/ventura pull request #142
Opened 2020-11-15 13:12 UTC by bramvanhoutte

Closes #73

2020-11-15 20:33 UTC, RobinWijnant requested changes

2020-11-15 20:33 UTC, RobinWijnant commented on src/components/Toaster/ToastManager/ToastManager.tsx
> +  bindNotify: (handler: ToastCallHandler) => void;
What does notify?

2020-11-15 20:33 UTC, RobinWijnant commented on src/components/Toaster/ToastManager/ToastManager.tsx
> +    const uniqueId = idCounter;
I think keeping state of the latest id can be avoided when using a Date() timestamp with ms as id

2020-11-15 20:33 UTC, RobinWijnant commented on src/components/Toaster/Toaster.test.tsx
> +    await waitFor(() => expect(toasterElement).not.toBeInTheDocument());
Nice <3

2020-11-15 20:51 UTC, bramvanhoutte commented on src/components/Toaster/Toast/Toast.tsx
> +    const [isShown, setIsShown] = useState(true);
This was so the ToastManager could close the toasts from the parent.

2020-11-18 13:18 UTC, RobinWijnant approved these changes

2020-11-18 13:23 UTC, merged